const express = require('express');
const router = express.Router();
const RiskFlag = require('../models/RiskFlag');
const Student = require('../models/Student');
const { authenticateToken: auth } = require('../middleware/auth');
const riskDetectionService = require('../services/riskDetectionService');
const logger = require('../utils/logger');

// Get risk flags with filtering
router.get('/', auth, async (req, res) => {
  try {
    const { studentId, type, severity, isActive, isResolved } = req.query;
    const query = { schoolId: req.user.schoolId };

    if (studentId) query.studentId = studentId;
    if (type) query.type = type;
    if (severity) query.severity = severity;
    if (isActive !== undefined) query.isActive = isActive === 'true';
    if (isResolved !== undefined) query.isResolved = isResolved === 'true';

    // For teachers, filter by their assigned students
    if (req.user.role === 'TEACHER') {
      const students = await Student.find({
        assignedTeacherId: req.user._id,
        schoolId: req.user.schoolId
      }).select('_id');
      query.studentId = { $in: students.map(s => s._id) };
    }

    const flags = await RiskFlag.find(query)
      .populate({
        path: 'studentId',
        select: 'firstName lastName fullName classroomId riskLevel guardianContacts',
        populate: {
          path: 'guardianContacts',
          select: 'name phone email relation'
        }
      })
      .populate('createdBy', 'name email')
      .populate('resolvedBy', 'name email')
      .sort({ createdAt: -1 });

    res.json({
      success: true,
      count: flags.length,
      data: flags
    });
  } catch (error) {
    logger.error('Error fetching risk flags:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch risk flags',
      error: error.message
    });
  }
});

// Get risk summary for school
router.get('/summary', auth, async (req, res) => {
  try {
    const summary = await RiskFlag.getSchoolSummary(req.user.schoolId);

    res.json({
      success: true,
      data: summary
    });
  } catch (error) {
    logger.error('Error fetching risk summary:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch risk summary',
      error: error.message
    });
  }
});

// Get risk summary for a student
router.get('/student/:studentId', auth, async (req, res) => {
  try {
    const { studentId } = req.params;
    const summary = await RiskFlag.getStudentSummary(studentId);

    res.json({
      success: true,
      data: summary
    });
  } catch (error) {
    logger.error('Error fetching student risk summary:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch student risk summary',
      error: error.message
    });
  }
});

// Create risk flag manually
router.post('/', auth, async (req, res) => {
  try {
    const flagData = {
      ...req.body,
      schoolId: req.user.schoolId,
      createdBy: req.user._id,
      autoGenerated: false
    };

    const flag = await RiskFlag.create(flagData);

    // Update student risk level
    await riskDetectionService.updateStudentRiskLevel(flag.studentId);

    res.status(201).json({
      success: true,
      message: 'Risk flag created successfully',
      data: flag
    });
  } catch (error) {
    logger.error('Error creating risk flag:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to create risk flag',
      error: error.message
    });
  }
});

// Run risk detection for a student
router.post('/detect/:studentId', auth, async (req, res) => {
  try {
    const { studentId } = req.params;

    const result = await riskDetectionService.detectRisksForStudent(
      studentId,
      req.user.schoolId,
      req.user._id
    );

    res.json({
      success: true,
      message: `Detected ${result.risksDetected} risks, created ${result.flagsCreated} flags`,
      data: result
    });
  } catch (error) {
    logger.error('Error detecting risks:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to detect risks',
      error: error.message
    });
  }
});

// Run risk detection for entire school (admin only)
router.post('/detect-all', auth, async (req, res) => {
  try {
    if (req.user.role !== 'ADMIN') {
      return res.status(403).json({
        success: false,
        message: 'Only administrators can run school-wide risk detection'
      });
    }

    // Run detection asynchronously
    riskDetectionService.detectRisksForSchool(req.user.schoolId, req.user._id)
      .then(result => {
        logger.info('School-wide risk detection completed', result);
      })
      .catch(error => {
        logger.error('School-wide risk detection failed:', error);
      });

    res.json({
      success: true,
      message: 'Risk detection started for all students. This may take a few minutes.'
    });
  } catch (error) {
    logger.error('Error starting risk detection:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to start risk detection',
      error: error.message
    });
  }
});

// Resolve risk flag
router.put('/:id/resolve', auth, async (req, res) => {
  try {
    const { id } = req.params;
    const { resolutionNotes } = req.body;

    const flag = await RiskFlag.findById(id);

    if (!flag) {
      return res.status(404).json({
        success: false,
        message: 'Risk flag not found'
      });
    }

    await flag.resolve(req.user._id, resolutionNotes);

    // Update student risk level
    await riskDetectionService.updateStudentRiskLevel(flag.studentId);

    res.json({
      success: true,
      message: 'Risk flag resolved successfully',
      data: flag
    });
  } catch (error) {
    logger.error('Error resolving risk flag:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to resolve risk flag',
      error: error.message
    });
  }
});

// Update risk flag
router.put('/:id', auth, async (req, res) => {
  try {
    const { id } = req.params;
    const updates = req.body;

    const flag = await RiskFlag.findByIdAndUpdate(
      id,
      updates,
      { new: true, runValidators: true }
    );

    if (!flag) {
      return res.status(404).json({
        success: false,
        message: 'Risk flag not found'
      });
    }

    // Update student risk level if severity changed
    if (updates.severity) {
      await riskDetectionService.updateStudentRiskLevel(flag.studentId);
    }

    res.json({
      success: true,
      message: 'Risk flag updated successfully',
      data: flag
    });
  } catch (error) {
    logger.error('Error updating risk flag:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to update risk flag',
      error: error.message
    });
  }
});

// Delete risk flag (admin only)
router.delete('/:id', auth, async (req, res) => {
  try {
    if (req.user.role !== 'ADMIN') {
      return res.status(403).json({
        success: false,
        message: 'Only administrators can delete risk flags'
      });
    }

    const { id } = req.params;
    const flag = await RiskFlag.findByIdAndDelete(id);

    if (!flag) {
      return res.status(404).json({
        success: false,
        message: 'Risk flag not found'
      });
    }

    // Update student risk level
    await riskDetectionService.updateStudentRiskLevel(flag.studentId);

    res.json({
      success: true,
      message: 'Risk flag deleted successfully'
    });
  } catch (error) {
    logger.error('Error deleting risk flag:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to delete risk flag',
      error: error.message
    });
  }
});

module.exports = router;
