const mongoose = require('mongoose');

const riskFlagSchema = new mongoose.Schema({
  studentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Student',
    required: [true, 'Student ID is required']
  },
  schoolId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'School',
    required: [true, 'School ID is required']
  },
  type: {
    type: String,
    enum: ['ATTENDANCE', 'PERFORMANCE', 'BEHAVIOR', 'SOCIOECONOMIC', 'COMBINED', 'OTHER'],
    required: [true, 'Risk type is required']
  },
  severity: {
    type: String,
    enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
    required: [true, 'Severity is required'],
    default: 'LOW'
  },
  title: {
    type: String,
    required: [true, 'Title is required'],
    trim: true,
    maxlength: [200, 'Title cannot exceed 200 characters']
  },
  description: {
    type: String,
    required: [true, 'Description is required'],
    trim: true,
    maxlength: [1000, 'Description cannot exceed 1000 characters']
  },
  data: {
    // Flexible field for storing risk-specific data
    attendanceData: {
      absences: Number,
      period: String,
      dates: [Date]
    },
    performanceData: {
      subject: String,
      currentScore: Number,
      previousScore: Number,
      drop: Number
    },
    socioeconomicData: {
      ubudeheLevel: Number,
      hasParents: Boolean,
      familyStability: Boolean
    },
    additionalInfo: mongoose.Schema.Types.Mixed
  },
  isActive: {
    type: Boolean,
    default: true
  },
  isResolved: {
    type: Boolean,
    default: false
  },
  resolvedAt: Date,
  resolvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  resolutionNotes: {
    type: String,
    trim: true,
    maxlength: [1000, 'Resolution notes cannot exceed 1000 characters']
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Created by user ID is required']
  },
  interventionId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Intervention'
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  ruleId: {
    type: String,
    trim: true
  }
}, {
  timestamps: true
});

// Indexes
riskFlagSchema.index({ studentId: 1, isActive: 1, severity: -1 });
riskFlagSchema.index({ schoolId: 1, isActive: 1, createdAt: -1 });
riskFlagSchema.index({ type: 1, severity: 1 });
riskFlagSchema.index({ isResolved: 1, createdAt: -1 });

// Method to resolve flag
riskFlagSchema.methods.resolve = function(userId, notes) {
  this.isResolved = true;
  this.isActive = false;
  this.resolvedAt = new Date();
  this.resolvedBy = userId;
  this.resolutionNotes = notes;
  return this.save();
};

// Static method to get risk summary by school
riskFlagSchema.statics.getSchoolSummary = async function(schoolId) {
  const flags = await this.find({ schoolId, isActive: true });

  const summary = {
    total: flags.length,
    critical: flags.filter(f => f.severity === 'CRITICAL').length,
    high: flags.filter(f => f.severity === 'HIGH').length,
    medium: flags.filter(f => f.severity === 'MEDIUM').length,
    low: flags.filter(f => f.severity === 'LOW').length,
    byType: {
      attendance: flags.filter(f => f.type === 'ATTENDANCE').length,
      performance: flags.filter(f => f.type === 'PERFORMANCE').length,
      behavior: flags.filter(f => f.type === 'BEHAVIOR').length,
      socioeconomic: flags.filter(f => f.type === 'SOCIOECONOMIC').length,
      combined: flags.filter(f => f.type === 'COMBINED').length,
      other: flags.filter(f => f.type === 'OTHER').length
    }
  };

  return summary;
};

// Static method to get student risk summary
riskFlagSchema.statics.getStudentSummary = async function(studentId) {
  const activeFlags = await this.find({ studentId, isActive: true }).sort({ severity: -1, createdAt: -1 });
  const resolvedFlags = await this.find({ studentId, isResolved: true }).sort({ resolvedAt: -1 }).limit(5);

  // Determine overall risk level
  let overallRisk = 'LOW';
  if (activeFlags.some(f => f.severity === 'CRITICAL')) {
    overallRisk = 'CRITICAL';
  } else if (activeFlags.some(f => f.severity === 'HIGH')) {
    overallRisk = 'HIGH';
  } else if (activeFlags.filter(f => f.severity === 'MEDIUM').length >= 2) {
    overallRisk = 'HIGH';
  } else if (activeFlags.some(f => f.severity === 'MEDIUM')) {
    overallRisk = 'MEDIUM';
  }

  return {
    overallRisk,
    activeFlags,
    resolvedFlags,
    counts: {
      active: activeFlags.length,
      resolved: resolvedFlags.length
    }
  };
};

module.exports = mongoose.model('RiskFlag', riskFlagSchema);
